Tilemaps
SLYGM/RetroEngineTM pull request #30
Opened 2023-02-23 16:43 UTC by MaximGorbach

Added tilemap support with capability for multiple tilemap and object layers, as well as using multiple tilesets.
Tilemaps must be exported from 'Tiled' in `.json` format, **with all tilesets embedded**. For more detailed documentation see the docs on `engine.TileMapJSONParser.parse`.
You can add new tilemap layers by going through the 'add layer' button on the UI.

> **Note:** Actually importing a tilemap is a bit scuffed at the moment, as the files have to be loaded from the `assets` directory currently to work. This means that you have to manually put the tileset images into the assets directory and change the paths in the `json` to point to them (if they don't already). This will require changing once we sort out how textures are loaded. 

> Another issue is that the tilemap `.json` can't be moved as this will mess up the relative paths to the tilesets contained within. To move it, you must re-export from Tiled into the desired location.

2023-03-14 17:45 UTC, Louis-Tarvin requested changes
Looks good, however the add layer dialogue seems bugged as there are duplicate fields.

2023-03-16 11:06 UTC, Louis-Tarvin requested changes
Just a couple of minor error handling suggestions. Other than that seems good

2023-03-16 11:06 UTC, Louis-Tarvin commented on pixelot/src/app/left-sidebar/left-sidebar.component.ts
> +          return;
I get console errors if I don't include a path or include an invalid json file. It looks like you've added the error handling in place here but for some reason it's not triggering?

2023-03-16 11:06 UTC, Louis-Tarvin commented on pixelot/src/app/left-sidebar/left-sidebar.component.ts
> +        new_layer = engine.TileMapJSONParser.parse(result.path);
Maybe wrap this in a try-catch and display a snackbar like above if parsing fails

2023-03-18 20:14 UTC, MaximGorbach commented
I've added the suggested error handling, and also fixed a bug where right clicking an entity would open the layer menu lol.

2023-03-19 11:18 UTC, Louis-Tarvin approved these changes

2023-03-19 11:31 UTC, merged